
- hosts: all
  gather_facts: False

  pre_tasks:
  - name: Debug vars (pre)
    debug: var=vars
  - name: Install Ansible prerequisites
    raw: sudo bash -c "test -e /usr/bin/python || (apt -qqy update && apt install -qy python-minimal)"
    changed_when: False
  - setup: # aka gather_facts

  tasks:
  - set_fact: params="{{ cloudforms | from_json }}"
  - name: Debug params (post)
    debug: var=params
    
  - name: Update system packages
    apt:
      upgrade: dist
      update_cache: yes

  - name: Install required packages
    apt: name={{ item }} state=present
    with_items:
    - mysql-server

  - name: Create MySQL database
    mysql_db: name={{ wp_database_name }} state=present
  
  - name: Create MySQL user
    mysql_user: 
      name={{ wp_database_user }} 
      password={{ wp_database_pass }}
      priv=*.*:ALL
