
- hosts: all
  # Only necessary if using pre_tasks
  gather_facts: False

  pre_tasks:
  - name: Debug vars (pre)
    debug: var=vars
  # Install packages needed for Ansible target
  - name: Install Python
    raw: sudo bash -c "test -e /usr/bin/python || (apt -qqy update && apt install -qy python-pip python-virtualenv)"
    changed_when: False
  - setup: # aka gather_facts
  - name: Install Python MySQL library
    pip: name=MySQL-python

  tasks:
  # Load & parse the Cloudforms variables into "params"
  - set_fact: params="{{ cloudforms | from_json }}"
  - name: Debug params (post)
    debug: var=params
    
  # Update packages
  - name: Update system packages
    apt:
      upgrade: dist
      update_cache: yes

  # Install prerequisite packages
  - name: Install required packages
    apt: name={{ item }} state=present
    with_items:
    - python-dev
    - libmysqlclient-dev
    - mysql-server
    - python-mysqldb

  # Create a new SQL database
  - name: Create MySQL database
    mysql_db: name={{ params.wp_database_name }} state=present
  
  # Create a new SQL user for the database
  - name: Create MySQL user
    mysql_user: 
      name={{ params.wp_database_user }} 
      password={{ params.wp_database_pass }}
      priv=*.*:ALL
